name: 'Setup fake-gcs-server'
description: 'Download & run fake-gcs-server container'
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        docker run -d --name fake-gcs-server -p 4443:4443 -v ${{ github.workspace }}/examples/gcs-data:/data fsouza/fake-gcs-server:1.52.1 -scheme http
        echo "Waiting for fake-gcs-server..."
        timeout 30s bash -c 'until curl -s http://localhost:4443/storage/v1/b; do sleep 1; done'
