// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package search

type Cveid struct {
	Name *string `json:"name"`
}

type CVEIdResult struct {
	Name       *string      `json:"name"`
	VulDesc    *string      `json:"VulDesc"`
	VulDetails []*VulDetail `json:"VulDetails"`
}

type CVEImgResult struct {
	Name *string   `json:"name"`
	Tags []*string `json:"tags"`
}

type ImgCVEResult struct {
	Tag       *string  `json:"tag"`
	CVEIdList []*Cveid `json:"CVEIdList"`
}

type VulDetail struct {
	PkgVendor  *string `json:"PkgVendor"`
	PkgName    *string `json:"PkgName"`
	PkgVersion *string `json:"PkgVersion"`
}
