name: Bug report
description: File a bug report
title: "[Bug]: " 
labels: bug
body:
  - type: input
    attributes: 
      label: "zot version"
      placeholder: "v1.4.3 or commit hash"
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Describe the bug"
      description: "Try to describe your issue/bug as well as you can, as that will help with speeding up fixing"

  - type: textarea
    attributes:
      label: "To reproduce"
      description: Steps to reproduce the behavior
      value: |
        1. Configuration
        2. Client tool used
        3. Seen error
        
  - type: textarea
    attributes:
      label: "Expected behavior"
      description: "A clear and concise description of what you expected to happen."
      
  - type: textarea
    attributes:
      label: "Screenshots"
      description: "If applicable, add screenshots to help explain your problem."

  - type: textarea
    attributes:
      label: "Additional context"
      description: "Add any other context about the problem here."
