apiVersion: v1
kind: Service
metadata:
  name: zot-exporter
  labels:
    app: zot-minimal
spec:
  ports:
  - name: zot-exporter
    port: 5051
    targetPort: zot-exporter
  selector:
    app: zot-minimal
  sessionAffinity: ClientIP

