name: "Lines of code statistics"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published

permissions: read-all

jobs:
  loc:
    name: Lines of code
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Install go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          cache: false
          check-latest: true
          go-version-file: .go-version
      - name: Install dependencies
        run: |
          cd $GITHUB_WORKSPACE
          go install github.com/hhatto/gocloc/cmd/gocloc@latest
      - name: All sources
        run: |
          cd $GITHUB_WORKSPACE
          gocloc .
      - name: All sources (except tests)
        run: |
          cd $GITHUB_WORKSPACE
          gocloc --not-match='.*_test.go' .
