name: enhancement-label
on:
  push:
    branches:
      - main
    
  pull_request:
    branches:
      - main
    types: [ labeled ]
jobs:
  enhancement-specific-stuff:
    if: ${{ github.event.label.name == 'enhancement' }}
    name: Enhancement Checks
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Hello world!"
