name: "Software License Check"
on:
  push:
    paths:
      - 'go.mod'
    branches:
      - main
  pull_request:
    paths:
      - 'go.mod'
    # The branches below must be a subset of the branches above
    branches: [main]

permissions: read-all

jobs:
  license-check:
    runs-on: ubuntu-latest
    name: License Check
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          cache: false
          check-latest: true
          go-version-file: .go-version
      - name: Install go-licenses
        run: go install github.com/google/go-licenses@latest
      - name: Check for forbidden licenses
        run: make check-licenses
      - name: Check if licenses file is updated
        run: make update-licenses
