name: 'Sync golang image from docker to ghcr'
on:
  schedule:
    - cron: '30 1 * * *'
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  sync-golang:
    name: 'sync'
    strategy:
      matrix:
        golang_version:
          - 1.18
          - 1.19
    runs-on: ubuntu-latest
    steps:
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Tag and push golang to ghcr
        run: |
          docker trust inspect golang:${{ matrix.golang_version }}
          docker pull golang:${{ matrix.golang_version }}
          docker tag golang:${{ matrix.golang_version }} ghcr.io/${{ github.repository_owner }}/golang:${{ matrix.golang_version }}
          docker push ghcr.io/${{ github.repository_owner }}/golang:${{ matrix.golang_version }}
