name: "Verify Example Config Files"

# Validate all example config files are relevant and valid.

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
  release:
    types:
      - published

permissions: read-all

jobs:
  verify-config:
    name: Verify Config Files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: ./.github/actions/build-zot-binaries
        with:
          make-targets: binary
          upload-artifact: "false"
      - name: run verify-config
        run: |
          cd $GITHUB_WORKSPACE
          make USE_PREBUILT=1 verify-config
